version: "3"

services:
  angular-app:
    build: ./docker/angular-app
    ports:
      - "4200:4200"
    volumes:
      - "./angular-app:/projects"
    tty: true
    entrypoint:
      - sh
    command:
      - -c
      - |
        npm install
        ng serve --host 0.0.0.0 --disable-host-check

  strapi-app:
    build: ./docker/strapi-app
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: "false"
    ports:
      - "1337:1337"
    volumes:
      - ./strapi-app:/opt/app
    working_dir: /opt/app
    depends_on:
      - mysql
    entrypoint:
      - sh
    command:
      - -c
      - |
        yarn install
        yarn develop
    tty: true

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    cap_add:
      - SYS_NICE
